### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by zombozo12** [remixer-dec/node-unnpk#2]
I just tried to unpack an npk and the node showed this error message.

       /usr/local/lib/node_modules/unnpk/unnpk.js:32

        let fparts = path.split("/");
        ^^^

      SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
         at exports.runInThisContext (vm.js:53:16)
         at Module._compile (module.js:374:25)
         at Object.Module._extensions..js (module.js:417:10)
         at Module.load (module.js:344:32)
         at Function.Module._load (module.js:301:12)
        at Function.Module.runMain (module.js:442:10)
        at startup (node.js:136:18)
        at node.js:966:3

**Comment by remixer-dec** [comment]
Looks like you're using a very old version of Node.
If you don't want to update it, you can try to add `'use strict'` in the second line of unnpk.js
